name: Validate

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    name: With hassfest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Hassfest validation
      uses: "home-assistant/actions/hassfest@master"

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v3"
      - name: Setup Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest
